name: Build Qt App (Linux & Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux]
        config: [Debug, Release]

    container:
      image: zofikar/qt-builder-${{ matrix.target }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and Build (${{ matrix.target }} - ${{ matrix.config }})
        run: |
          cmake -S . -B build-${{ matrix.target }}-${{ matrix.config }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          find . -type f -exec touch {} +
          cmake --build build-${{ matrix.target }}-${{ matrix.config }} --config ${{ matrix.config }}
           tar -zcf ./build-${{ matrix.target }}-${{ matrix.config }}.tar.gz ./build-${{ matrix.target }}-${{ matrix.config }}/

      - name: Upload artifact (${{ matrix.target }} - ${{ matrix.config }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.config }}-build
          path: build-${{ matrix.target }}-${{ matrix.config }}/*
